# Generated by Django 2.1.7 on 2019-03-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('lastcommitsha', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.CharField(max_length=200)),
            ],
        ),
    ]
