# Generated by Django 2.1.7 on 2019-03-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicaltest', '0002_auto_20190328_2341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RootEndPoint',
            new_name='Home',
        ),
        migrations.RenameModel(
            old_name='MetaDataEndPoint',
            new_name='Meta',
        ),
    ]
