# Generated by Django 2.1.7 on 2019-03-29 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicaltest', '0003_auto_20190329_0145'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meta',
            new_name='MetaData',
        ),
    ]
