# Generated by Django 2.1.7 on 2019-03-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicaltest', '0004_auto_20190329_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='lastcommitsha',
            new_name='last_commit_sha',
        ),
        migrations.AddField(
            model_name='metadata',
            name='commit_message',
            field=models.CharField(default='Code Commit', max_length=200),
        ),
    ]
